# Vault Secret Mappings for Dockhand
# This file defines which secrets to fetch from HashiCorp Vault

vault:
  # Default path for all secrets (can be overridden per-secret)
  path: secret/data/dockhand-test
  # Global setting: trigger redeploy when ANY secret changes (default: false)
  triggerRedeploy: false

secrets:
  # Simple mapping: environment variable name = Vault key name
  - DATABASE_PASSWORD

  # Explicit mapping with different Vault key
  - name: API_KEY
    key: api_key

  # Secret that triggers automatic redeploy when changed
  - name: ADMIN_TOKEN
    key: admin_token
    triggerRedeploy: true
